### ISSUE TITLE
Test for editing a pet with an existing owner selects multiple owners

### ISSUE THREAD

**Issue by kjleitz** [learn-co-students/sinatra-complex-forms-associations-v-000#271]
This test, starting on line 91 of `spec/controllers/pets_controller_spec.rb`:

```ruby
    it "edit's the pet's owner with an existing owner" do
      @adam = Owner.create(:name => "Adam")
      visit "/pets/#{@pet.id}/edit"
      check(@adam.id)
      click_button "Update Pet"
      expect(Pet.last.owner.name).to eq("Adam")
    end
```

...assumes that no other checkboxes are checked for the owner of the existing pet. It just checks Adam's box and submits it. This should really be a radio button anyway, but it means that the owner is ambiguous, and, depending on your logic, is likely going to be the first checkbox `owner_id` that is returned (i.e. the original owner, since they are probably going to have a lower `id` than Adam's).

This can be solved by using radio buttons instead, or unchecking the original owner. It's not solved by leaving all the checkboxes unchecked because the spec also specifies that the original owner's checkbox is checked on the edit page.

**Comment by kjleitz** [comment]
For that matter, the test immediately following it (starting on line 99):

```ruby
    it "edit's the pet's owner with a new owner" do
      visit "/pets/#{@pet.id}/edit"
      fill_in "owner_name", :with => "Samantha"
      click_button "Update Pet"
      expect(Pet.last.owner.name).to eq("Samantha")
    end
```

...also leaves the original checkbox checked when filling in the "new owner" field, creating another ambiguity. If your logic in the controller checks to see if there's something in that field, and then creates the owner based on that new name and disregards the checkboxes, that's great. If you do the inverse and check to see if there are checked checkboxes, and then uses the owner based on that checkbox and disregards the "new owner" name field, then you have a problem--it will use the original owner.

**Comment by cernanb** [comment]
Fixed
